"""update

Revision ID: 12299d85b520
Revises: 2b408855ba9a
Create Date: 2025-09-10 11:03:07.999173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12299d85b520'
down_revision = '2b408855ba9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clean_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_video', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('folder_video', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clean_data', schema=None) as batch_op:
        batch_op.drop_column('folder_video')
        batch_op.drop_column('link_video')

    # ### end Alembic commands ###
