"""update

Revision ID: 49bea8b7013f
Revises: 5d2634ee9f88
Create Date: 2025-09-24 15:35:25.805746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bea8b7013f'
down_revision = '5d2634ee9f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenshot_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.Text(), nullable=False))
        batch_op.alter_column('screenshot_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenshot_data', schema=None) as batch_op:
        batch_op.alter_column('screenshot_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('label')

    # ### end Alembic commands ###
