"""update

Revision ID: 5d2634ee9f88
Revises: 12299d85b520
Create Date: 2025-09-19 06:26:23.642342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d2634ee9f88'
down_revision = '12299d85b520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clean_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segments', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clean_data', schema=None) as batch_op:
        batch_op.drop_column('segments')

    # ### end Alembic commands ###
